@startuml

hide circle
skinparam classAttributeIconSize 0

class User

class Model

class Storage

class Ui

class Logic

class Main

User --> Ui : interacts >


Main --> Model
Main --> Logic
Main -> Storage

Storage -> Model

Logic --> Model
Logic ..> Ui
@enduml