@startuml

hide circle
skinparam classAttributeIconSize 0

class User

class Model

class Storage

class Ui

class Logic

class Main

User --> Ui : interacts >

Ui -> Model
Ui --> Logic

Main --> Model
Main --> Logic
Main -> Storage
Main --> Ui

Storage -> Model

Logic --> Model
@enduml